version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    env_file: .env  # env variables
    ports:
      - '4467:4467'
    environment:
      PRISMA_CONFIG: |
        port: 4467
        databases:
          default:
            connector: postgres
            host: postgres
            database: ${POSTGRES_DB}
            port: 5432
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
  postgres:
    image: postgres:10.3
    container_name: linkedin_db
    env_file: .env  # env variables
    ports:
      - '5433:5432'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
