version: '3'
services:
  web:
    build: .
    depends_on:
      - prisma
    env_file: .env  # env variables
    ports:
      - "5000:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  prisma:
    ports:
      - '4468:4467'
