version: '3'
services:
  web:
    build: .
    depends_on:
      - prisma
    env_file: .env  # env variables
    ports:
      - "5000:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4467:4467'
    environment:
      PRISMA_CONFIG: |
        port: 4467
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
