version: '3'
services:
  web:
    image: node:10
    env_file: .env  # env variables
    working_dir: /usr/src/app
    command: ./scripts/wait-for-it.sh ${PRISMA_ENDPOINT} -- bash -c "npm start"
    environment:
      - DEBUG=1
    ports:
      - "5000:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - '4467:4467'
